export default {
    GET_SEARCH_DATA_WITH_JSON_REQUEST: "GET_SEARCH_DATA_WITH_JSON_REQUEST",
    GET_SEARCH_DATA_WITH_JSON_SUCCESS: "GET_SEARCH_DATA_WITH_JSON_SUCCESS",
    GET_SEARCH_DATA_WITH_JSON_FAIL: "GET_SEARCH_DATA_WITH_JSON_FAIL",
    GET_SEARCH_DATA_REQUEST: "GET_SEARCH_DATA_REQUEST",
    GET_SEARCH_DATA_SUCCESS: "GET_SEARCH_DATA_SUCCESS",
    GET_SEARCH_DATA_FAIL: "GET_SEARCH_DATA_FAIL",
};
